INDIGO_WELCOME_MESSAGE: "جــــامعة السلطــــان مـولاي سليمــــان"
INDIGO_PRIMARY_COLOR: "#470701" # cool blue

# Footer links are dictionaries with a "title" and "url"
# To remove all links, write:
# INDIGO_FOOTER_NAV_LINKS: []
# INDIGO_FOOTER_LEGAL_LINKS: []
INDIGO_FOOTER_NAV_LINKS:
  - title: "About"
    url: "/about"
  - title: "Contact"
    url: "/contact"
INDIGO_FOOTER_LEGAL_LINKS:
    - title: "Terms of service"
      url: "/tos"
    - title: "Université Sultan Moulay Slimane | Portail officiel de l'USMS"
      url: "http://www.usms.ac.ma/website/"
